package com.anfly.wanandroidbig.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.ceshi1.Bean.FooDbBean;

import com.anfly.wanandroidbig.dao.FooDbBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig fooDbBeanDaoConfig;

    private final FooDbBeanDao fooDbBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        fooDbBeanDaoConfig = daoConfigMap.get(FooDbBeanDao.class).clone();
        fooDbBeanDaoConfig.initIdentityScope(type);

        fooDbBeanDao = new FooDbBeanDao(fooDbBeanDaoConfig, this);

        registerDao(FooDbBean.class, fooDbBeanDao);
    }
    
    public void clear() {
        fooDbBeanDaoConfig.clearIdentityScope();
    }

    public FooDbBeanDao getFooDbBeanDao() {
        return fooDbBeanDao;
    }

}
