package com.anfly.wanandroidbig.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.mode02.Bean.FoodDBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "FOOD_DBEAN".
*/
public class FoodDBeanDao extends AbstractDao<FoodDBean, Long> {

    public static final String TABLENAME = "FOOD_DBEAN";

    /**
     * Properties of entity FoodDBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Des = new Property(1, String.class, "des", false, "DES");
        public final static Property Pri = new Property(2, String.class, "pri", false, "PRI");
    }


    public FoodDBeanDao(DaoConfig config) {
        super(config);
    }
    
    public FoodDBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"FOOD_DBEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"DES\" TEXT," + // 1: des
                "\"PRI\" TEXT);"); // 2: pri
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"FOOD_DBEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, FoodDBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String des = entity.getDes();
        if (des != null) {
            stmt.bindString(2, des);
        }
 
        String pri = entity.getPri();
        if (pri != null) {
            stmt.bindString(3, pri);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, FoodDBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String des = entity.getDes();
        if (des != null) {
            stmt.bindString(2, des);
        }
 
        String pri = entity.getPri();
        if (pri != null) {
            stmt.bindString(3, pri);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public FoodDBean readEntity(Cursor cursor, int offset) {
        FoodDBean entity = new FoodDBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // des
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // pri
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, FoodDBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setDes(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setPri(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(FoodDBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(FoodDBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(FoodDBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
